stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - name: compile
      stage: compile
      language: node_js
      node_js: 10
      cache:
        directories:
          - node_modules
      install:
        - npm install
      script: npm run build
      deploy:
        provider: s3
        bucket: "lukekennedy-net-travis"
        region: ap-southeast-2
        skip_cleanup: true
        local_dir: build
        upload_dir: ui/$TRAVIS_BUILD_NUMBER
        on:
          tags: true
    - name: test
      stage: test
      language: node_js
      node_js: 10
      cache:
        directories:
          - node_modules
      install:
        - npm install
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: npm run coveralls
      after_script:
        # - codeclimate < coverage/**/lcov.info
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - name: deploy
      stage: deploy
      language: node_js
      node_js: 10
      cache:
        directories:
          - node_modules
      install:
        - npm install
      script: exit 0 # write deployment code